### ISSUE TITLE
Number of keywords

### ISSUE THREAD

**Issue by mvdberk** [jabberjabberjabber/LLavaImageTagger#1]
Hi, thank you this great program! My usage would be tagging images to sell as stock photography. Your tool autmatically does what I did manually for years. I have a question: is there a way to increase/set the number of keywords? When testing it only genereted 7 keywords or so. Most stocksites require around 30.

**Comment by jabberjabberjabber** [comment]
You can change the prompt to request it. Open the llmii.py file and find 'metadata_instruction':

```
self.metadata_instruction = "The following caption and metadata was given for an image. Use that to determine the title, IPTC keywords, summary, and subject. Return as JSON object with keys Title, Keywords, Summary, and Subject.\n"
```
Change that to be something like 

```
self.metadata_instruction = "The following caption and metadata was given for an image. Use that to determine the title, summary, and subject and generate 30 keywords. Return as JSON object with keys Title, Keywords, Summary, and Subject.\n"
```

Since it is a language model you can just ask it to do what you want. However you have to make sure it doesn't get confused too much because it needs to respond with a somewhat useable JSON object in order to match the metadata tags.

**Comment by jabberjabberjabber** [comment]
Oh I forgot, you will also have to increase the generation length. Find this section:

````
    def describe_content(self, instruction="", content=""):
        prompt = self.get_prompt(instruction, content)
        payload = {
            "prompt": prompt,
            "max_length": 256,
            "genkey": self.genkey,
            "top_p": 1,
            "top_k": 0,
            "temp": 0.5,
            "rep_pen": 1,
            "min_p": 0.05,
        }

        return self._call_api("generate", payload)
        
````

And change the number after max_length. It is in tokens and each token is about half a word, so if it is cutting off before you get 30 keywords change it to 300 or 350 and see what you get.

**Comment by jabberjabberjabber** [comment]
I updated the script to add a keyword number field. It will attempt to create the number of keywords you specify in the box. The more you have it attempt, the longer it will take and it might possibly give erratic output. I was only able to get it to go between 20 and 30 by putting 30 in the box so you might have to specify more than you want (language models are terrible at estimating their own outputs because they don't 'think' in words, they 'think' in tokens). Also play with the image instruction (caption) prompt -- try having it generate keywords there and it will reuse them in the subsequent turn. Also, try running another language model. Go on huggingface and find a gguf, then match a projector with it. For example Llama-3-8b models can use any Llama-3-8b projector. Projectors are named 'mmproj'. Caution -- trying to figure out the current state of language models and their naming schemes can be a real challenge. Head over to /r/locallama on reddit if you need help.

**Comment by saket424** [comment]
@jabberjabberjabber 
Fantastic work! I hadn't even heard of kobold till I saw you post of reddit

https://www.reddit.com/r/LocalLLaMA/comments/1f7cdhj/koboldcpp_and_vision_models_a_guide/

The MiniCPM-V2.6 model 4-bit quantized version is very usable on my Mac.

Thanks again
