### ISSUE TITLE
Can we have a lightweight/fast model?

### ISSUE THREAD

**Issue by pandayummy** [jabberjabberjabber/LLavaImageTagger#2]
6GB model is too slow to inference, can we have a lightweight and fast smaller model?

**Comment by kawaii2020** [comment]
![image](https://github.com/user-attachments/assets/62fd0d32-8a21-418a-aba4-7157b6568f08)

How to change the model to sfr-iterative-dpo-llama-3-8b-r-imat-IQ1_S.gguf ?

**Comment by jabberjabberjabber** [comment]
You can use any model you like. There are few different methods to do this:

1. Edit llmii.kcppt in a text editor and change the fields for "mmproj" and/or "model_param" (they have to match, so if you change to a non-llama3 based LLM you need to get a projector the base model that one is using). The kcppt uses a JSON schema so look only change the part inside the quotes otherwise you will break it.
2. Download a new gguf and rename it the same as the one in the folder (bad idea since it can be confusing)
3. Open koboldcpp.exe manually, use it to load the model and projector of your choice, then run llmii-no-kobold.bat

I will warn you that if you try to use a model too lightweight it will give bad information or more likely just not work because it will be dumb to output a JSON object. IQ-1S is going to be unusable as it only uses 1 bit (the original was 32) for each parameter in the model.  Look up the the difference between gguf quants for more information.
