### ISSUE TITLE
[FR] support user dicts for controlled vocabulatary / taxonomy ?

### ISSUE THREAD

**Issue by cannibalox** [jabberjabberjabber/LLavaImageTagger#6]
hey @jabberjabberjabber , thank you for the great script !
do you have any suggestions on workflows to support controlled vocabulary like the IPTC Media Topics ? 
http://www.photometadata.org/META-Resources-Field-Guide-to-Metadata#IPTC%20Subject%20Code
https://www.iptc.org/std/NewsCodes/treeview/mediatopic/mediatopic-en-GB.html

I've tried tweaking the `system_instruction` and prompt but models like llama 3 8B and MiniCPM-V-2.6 seem to hallucinate most of the categories. Ideally I would love a way to feed a custom thesaurus then instruct the model to only grab keywords from that thesaurus. Any pointers would be welcome.

**Comment by jabberjabberjabber** [comment]
Unfortunately the prompts are useless for this -- LLMs are terrible at picking out of a limited number of options. You can use grammar to do it (gnbf) but it slows down the inference considerably.

* https://github.com/ggerganov/llama.cpp/tree/master/grammars

To use it greate your grammar file as a grammar.gnbf or whatever and add it to the prompt payload. Something like this:

```
        if os.path.exists(grammar_file_path):
            with open(grammar_file_path, 'r') as f:
                grammar_file = f.read()
                
        payload = {
            "prompt": prompt,
            "max_length": 250,
            "genkey": self.genkey,
            "temp": 0,
            "grammar": grammar_file
        }
```

**Comment by jabberjabberjabber** [comment]
FYI I am working on another script that will compliment this. It goes through all image keywords and semantically either deduplicates or expands them (remove all words in group and replace with a common, or add all words of group to all members which have one of the group words). It is going OK but I want to get it to work with limited supervision which is tough because you end up with it grouping things like 'personal' with 'personality'. If that would solve your problem let me know and I will share what I have done so far.

**Comment by cannibalox** [comment]
Hi ! thanks for the tip, I'll look into the gnbf workflow. 
Your other script sound very interesting indeed, if you don't mind sharing, I would love to try it ! 
It's challenging to get consistent keywords, the image description usually works great (using one of your older versions) but I'm struggling with tags, it's not so much about false positives, but lots of aliases and synonyms that should be consolidated, so it sounds like your new script might be really helpful :)

**Comment by jabberjabberjabber** [comment]
> Hi ! thanks for the tip, I'll look into the gnbf workflow. Your other script sound very interesting indeed, if you don't mind sharing, I would love to try it ! It's challenging to get consistent keywords, the image description usually works great (using one of your older versions) but I'm struggling with tags, it's not so much about false positives, but lots of aliases and synonyms that should be consolidated, so it sounds like your new script might be really helpful :)

I knew that would be the case from the start. This script is going to be one part of a whole file-system auto-organizing system run by AI. Since I am learning as I go I decided to do it all piecemeal. A unified keyword system is the next piece.

I will let you know when I get a barely working version of the keyword consolidation/expansion script.

**Comment by jabberjabberjabber** [comment]
Would you be willing to hop in the koboldcpp discord server? I'd like to be able to message without using a github issue.

**Comment by cannibalox** [comment]
> Would you be willing to hop in the koboldcpp discord server? I'd like to be able to message without using a github issue.

sure! you can dm id: 542766921452355595

**Comment by jabberjabberjabber** [comment]
Updated version will now expand or dedupe keywords. Hope this helps with your use case but unfortunately in order to get a model to comply with a limited selection of options would involve a lot more complexity or require use of a non-local API.

**Comment by cannibalox** [comment]
thank you very much for the update l it's already a huge time saver for me as it is
