### ISSUE TITLE
How do I change the model to be used?

### ISSUE THREAD

**Issue by peterchanws** [jabberjabberjabber/LLavaImageTagger#7]
Thank you for your work. I’m an archivist at Stanford Libraries, and I’m considering using this program to describe images in some of our collections. I’m currently using a MacBook Pro running macOS 15.2.

I’d like to test the keywords generated by different LLMs. To do this, I’ve loaded airoboros-mistral2.2-7b.Q4_K_S.gguf into LLavaImageTagger.

**Comment by jabberjabberjabber** [comment]
Either change the model and the projector in the kcppt file or load them with koboldcpp using the launcher and run llmii-gui.py using python.

But you are going to have a problem because the model you want to use doesn't have an image projector. See [this guide](https://www.reddit.com/r/LocalLLaMA/comments/1f7cdhj/koboldcpp_and_vision_models_a_guide/) for information on how vision models work with kobold.

**Comment by jabberjabberjabber** [comment]
[Here are basically all the available image projectors.](https://huggingface.co/koboldcpp/kcppt/tree/main)
